### ISSUE TITLE
Hosting in a sub directory / not root directory

### ISSUE THREAD

**Issue by ghost** [erintheunready/ComicControl#5]
I've tried to set up comic control in a sub directory  `/comic/` ie. `www.mywebsite.com/comic/` but after the ComicControl Easy Installer I'm having 2 issues at the moment. 

The biggest issue is not being able to add storylines  - the storyline form isn't appearing, so I'm unable to post any comics since storylines are a mandatory field in making a comic post. I should note that this is done with a hosting provider I'm not sure how to install xdebug, _(can I do it through cpanel ?)_. so I just have the screenshots for now. 

![sub directory error storyline](https://user-images.githubusercontent.com/45357640/105360922-1678c380-5c34-11eb-817c-a79d440ac0ab.PNG)

Another minor issue is that the Images also aren't showing up.  When I upload them and afterwards, but using FTP I can see the files do exist.  

![sub directory add image ](https://user-images.githubusercontent.com/45357640/105361428-a3238180-5c34-11eb-95fd-56492c080176.PNG)

**Comment by erintheunready** [comment]
Hi,
Apologies for the issues--I've had less opportunities to test these scenarios but I believe I've fixed the relevant issues.  Please try updating your version and see if that fixes things.  If not, try re-downloading ComicControl and overwriting your current files with the current version (this will not remove your installation, this is essentially a manual upgrade).

**Comment by ghost** [comment]
No that's okay, thank you for all your help so far, it means alot. 
I tried changing the /comiccontrol/ folder and then I tried a total refresh and trying to reinstall the site from scratch with the new version but it hasn't fixed the Storyline form error not loading. I'm getting a new bug but I'll open it as new issue.

**Comment by erintheunready** [comment]
Thank you, I will looks specifically at that bug if the other ones are fixed.
