### ISSUE TITLE
Update warning

### ISSUE THREAD

**Issue by ghost** [erintheunready/ComicControl#6]
So I know I have the latest version but I'm still getting update warnings after I login

![update warning error](https://user-images.githubusercontent.com/45357640/105361917-2f35a900-5c35-11eb-8517-45c261356e07.PNG)

If I then click on the red _Click here to update your site!_ or _Check for Updates_ link in the sidebar I'm taken `/comiccontrol/update-check` where I get another more detailed error

![update page](https://user-images.githubusercontent.com/45357640/105362251-a408e300-5c35-11eb-9dde-5113065701ee.PNG)

And then clicking on the _Upgrade ComicControl_ causes the following error that confirms I have the latest version.

![update error](https://user-images.githubusercontent.com/45357640/105362414-d6b2db80-5c35-11eb-9472-c2fcbdaa0139.PNG)

But heading back to the dashboard the original errors are still there. 
How do I get rid of the update warnings?

**Comment by erintheunready** [comment]
Hi, this has been fixed as of 4.2.1 release but you may have to do a clean re-install.  However if you don't want to do that, you can use phpMyAdmin or another MySQL editor to change your cc_yoursite_options table to set the value of "version" to 4.2.0 to fix this.  If you update after that things should work properly.  Let me know if that solution does not work; if it does work, please let me know and I will close this issue.

**Comment by ghost** [comment]
I've done a clean re-install of my site and I'm not getting the errors anymore. Thank you.

![updates](https://user-images.githubusercontent.com/45357640/105466711-9dc74500-5ccf-11eb-908c-7c2d4883d09d.PNG)
