### ISSUE TITLE
php short open tags are deprecated

### ISSUE THREAD

**Issue by Zaidyer** [erintheunready/ComicControl#8]
php short open tags `<?` are officially deprecated and as such, web hosts are disabling the ability to use them by default. My own web host disallows their use entirely.

I was able to work around this problem by using **Notepad++** to replace all short open tags using a regular expression:
Find: `<\?(?!php)(?!=)`
Replace with: `<?php`

Then I replaced the short echo tags as follows:
Find: `<?=`
Replace with: `<?php echo ` (note that a space is at the end so that "echo" is read correctly instead of becoming part of another word)

The results appear to be functional and I was able to install ComicControl on my website.

**Comment by erintheunready** [comment]
Hi Zaidyer,
I will try to replace all the short tags today, didn't realize they've been deprecated.  I will let you know when the update is released but once that's done you should be able to safely update and have the CC install work properly.

**Comment by erintheunready** [comment]
> php short open tags `<?` are officially deprecated and as such, web hosts are disabling the ability to use them by default. My own web host disallows their use entirely.
> 
> I was able to work around this problem by using **Notepad++** to replace all short open tags using a regular expression:
> Find: `<\?(?!php)(?!=)`
> Replace with: `<?php`
> 
> Then I replaced the short echo tags as follows:
> Find: `<?=`
> Replace with: `<?php echo ` (note that a space is at the end so that "echo" is read correctly instead of becoming part of another word)
> 
> The results appear to be functional and I was able to install ComicControl on my website.

Question for you since you are experiencing this on your version (this appears to be only an issue in 7.4, which I don't have on my servers yet): are you getting errors for <?= if you leave them? I'm reading about the deprecation and it doesn't appear to include those instances.  If you could, please check for me, or I can see if I have a PHP update available on our WHM installs.

**Comment by Zaidyer** [comment]
> 
> 
> > php short open tags `<?` are officially deprecated and as such, web hosts are disabling the ability to use them by default. My own web host disallows their use entirely.
> > I was able to work around this problem by using **Notepad++** to replace all short open tags using a regular expression:
> > Find: `<\?(?!php)(?!=)`
> > Replace with: `<?php`
> > Then I replaced the short echo tags as follows:
> > Find: `<?=`
> > Replace with: `<?php echo ` (note that a space is at the end so that "echo" is read correctly instead of becoming part of another word)
> > The results appear to be functional and I was able to install ComicControl on my website.
> 
> Question for you since you are experiencing this on your version (this appears to be only an issue in 7.4, which I don't have on my servers yet): are you getting errors for <?= if you leave them? I'm reading about the deprecation and it doesn't appear to include those instances. If you could, please check for me, or I can see if I have a PHP update available on our WHM installs.

Leaving the `<?=` tags _appeared_ to work at first, but I was getting odd instances of empty menu items and unresponsive buttons. Those problems may be due to a server configuration issue on my end, but I don't yet know what it could possibly be.
I do know that nothing appears to be broken or malfunctioning when they're replaced with full `<?php echo ` tags.

**Comment by erintheunready** [comment]
> > > php short open tags `<?` are officially deprecated and as such, web hosts are disabling the ability to use them by default. My own web host disallows their use entirely.
> > > I was able to work around this problem by using **Notepad++** to replace all short open tags using a regular expression:
> > > Find: `<\?(?!php)(?!=)`
> > > Replace with: `<?php`
> > > Then I replaced the short echo tags as follows:
> > > Find: `<?=`
> > > Replace with: `<?php echo ` (note that a space is at the end so that "echo" is read correctly instead of becoming part of another word)
> > > The results appear to be functional and I was able to install ComicControl on my website.
> > 
> > 
> > Question for you since you are experiencing this on your version (this appears to be only an issue in 7.4, which I don't have on my servers yet): are you getting errors for <?= if you leave them? I'm reading about the deprecation and it doesn't appear to include those instances. If you could, please check for me, or I can see if I have a PHP update available on our WHM installs.
> 
> Leaving the `<?=` tags _appeared_ to work at first, but I was getting odd instances of empty menu items and unresponsive buttons. Those problems may be due to a server configuration issue on my end, but I don't yet know what it could possibly be.
> I do know that nothing appears to be broken or malfunctioning when they're replaced with full `<?php echo ` tags.

Hi Zaidyer, can you download the most recent version I have here on GitHub and replace your current files with those files? I did not replace the <?= tags but I want to see if it works as-is before replacing all of those.

**Comment by Zaidyer** [comment]
> 
> 
> > > > php short open tags `<?` are officially deprecated and as such, web hosts are disabling the ability to use them by default. My own web host disallows their use entirely.
> > > > I was able to work around this problem by using **Notepad++** to replace all short open tags using a regular expression:
> > > > Find: `<\?(?!php)(?!=)`
> > > > Replace with: `<?php`
> > > > Then I replaced the short echo tags as follows:
> > > > Find: `<?=`
> > > > Replace with: `<?php echo ` (note that a space is at the end so that "echo" is read correctly instead of becoming part of another word)
> > > > The results appear to be functional and I was able to install ComicControl on my website.
> > > 
> > > 
> > > Question for you since you are experiencing this on your version (this appears to be only an issue in 7.4, which I don't have on my servers yet): are you getting errors for <?= if you leave them? I'm reading about the deprecation and it doesn't appear to include those instances. If you could, please check for me, or I can see if I have a PHP update available on our WHM installs.
> > 
> > 
> > Leaving the `<?=` tags _appeared_ to work at first, but I was getting odd instances of empty menu items and unresponsive buttons. Those problems may be due to a server configuration issue on my end, but I don't yet know what it could possibly be.
> > I do know that nothing appears to be broken or malfunctioning when they're replaced with full `<?php echo ` tags.
> 
> Hi Zaidyer, can you download the most recent version I have here on GitHub and replace your current files with those files? I did not replace the <?= tags but I want to see if it works as-is before replacing all of those.

Done. Seems to be working just fine and performing smoothly even with `<?=` tags.
